#!/bin/sh
DIASPORA_HOME="/home/lprelle/diaspora"
REDIS_CONFIG="/home/lprelle/redis-2.4.7/redis.conf"
RETVAL=0
datum=`date`

start() {
        cd $DIASPORA_HOME
        echo starting god
	echo `god --log-level error -D -c 'script/diaspora.god' &` &
}

stop() {

        echo `ps aux | grep god | grep -v grep | awk -F " "  '{ print $2}' | xargs kill`
        echo `ps aux | grep sidekiq | grep -v grep | awk -F " "  '{ print $2}' | xargs kill`
        echo `ps aux | grep unicorn | grep -v grep | awk -F " "  '{ print $2}' | xargs kill`
}

bilderbackup() {
        echo `find /home/lprelle/diaspora/public/uploads/images ! -name 'scal*' -and ! -name 'thumb*' -exec cp {} /home/lprelle/bilderbackup/ \;`
}

update() {
        cd $DIASPORA_HOME
        echo pulling from github
        git pull origin despora
        echo setting commit on splashpage
        COMMIT=`git show | sed -n 1p  | awk {'print $2'}`
#       OUTPUT=`git rev-list --parents -1 $COMMIT | awk {'print $3'}`
        echo `sed -i "s#.*https://github.com/despora/diaspora/commit.*#            \%a{:href \=\> \"https://github.com/despora/diaspora/commit/$COMMIT\", \:target \=\> \"\_blank\"\} $COMMIT#g" /home/lprelle/diaspora/app/views/home/_show.html.haml`
        echo installing gems
        bundle install
        echo migrating db
        RAILS_ENV=production bundle exec rake db:migrate
        echo bundle exec rake assets:precompile
        RAILS_ENV=production bundle exec rake assets:precompile
}

case "$1" in
   start)
      start
      ;;
   stop)
      stop
      ;;
   restart)
      stop
      start
      ;;
   update)
      update
      stop
      ;;
   justupdate)
      update
      ;;
   bilderbackup)
      bilderbackup
      ;;
   *)
      echo $"Usage: diaspora { start | stop | restart | update | bilderbackup }"
      RETVAL=3
esac

exit $RETVAL
